<?php
/**
 * @param $oldversion
 *
 * @return bool
 */
function xmldb_block_glsubs_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    /// Add a new column newcol to the mdl_myqtype_options


    if ($oldversion < 2016101002) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.

        // Define field newcategories to be added to block_glsubs_glossaries_subs.
        $table = new xmldb_table('block_glsubs_glossaries_subs');
        $field = new xmldb_field('newcategories', XMLDB_TYPE_INTEGER, '1', null, null, null, null, 'active');

        // Conditionally launch add field newcategories.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Define field newentriesuncategorised to be added to block_glsubs_glossaries_subs.
        $table = new xmldb_table('block_glsubs_glossaries_subs');
        $field = new xmldb_field('newentriesuncategorised', XMLDB_TYPE_INTEGER, '1', null, null, null, null, 'newcategories');

        // Conditionally launch add field newentriesuncategorised.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Define field timecreated to be added to block_glsubs_event_subs_log.
        $table = new xmldb_table('block_glsubs_event_subs_log');
        $field = new xmldb_field('timecreated', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null, 'eventlink');

        // Conditionally launch add field timecreated.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Define field timeprocessed to be added to block_glsubs_event_subs_log.
        $table = new xmldb_table('block_glsubs_event_subs_log');
        $field = new xmldb_field('timeprocessed', XMLDB_TYPE_INTEGER, '10', null, null, null, null, 'timecreated');

        // Conditionally launch add field timeprocessed.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Define field active to be added to block_glsubs_authors_subs.
        $table = new xmldb_table('block_glsubs_authors_subs');
        $field = new xmldb_field('active', XMLDB_TYPE_INTEGER, '1', null, null, null, null, 'authorid');

        // Conditionally launch add field active.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Glsubs savepoint reached.
        upgrade_block_savepoint(true, 2016101002 , 'glsubs');
    }

    return true;
}